departments = {
"College of Social Work": [
    "Youth Development",
    "School Partnerships",
    "Exercise Science",
    "School Social Work",
    "Social Policy for Older Adults",
    "Service Delivery Systems for Older Adults and Victims of Violence",
    "Evaluation & Assessment Methods",
    "Positive Youth Development",
    "Mixed Methods Research",
    "Experiential Learning",
    "Self-care for Women in Academia",
    "School Research",
    "Social Justice Issues in Education",
    "Research Methods",
    "HIV",
    "Sexual Health",
    "Families",
    "Protective Factors",
    "Health Disparities",
    "Psychotherapy",
    "Family Therapy",
    "Technology-Based Care",
    "Clinical Treatment Development",
    "Social Work Curriculum Development",
    "Qualitative Research Methods",
    "Substance Use Disorder Treatment and Recovery",
    "Writing for Publication",
    "Critical Theory",
    "Poverty Discourse",
    "Homelessness",
    "Community Responses",
    "Guaranteed Income Research",
    "Child Welfare",
    "Adolescent Mental Health",
    "Technology and Social Work",
    "Safety and Risk Assessment",
    "Linking Services to Family Needs",
    "Aging",
    "Family Care Giving",
    "Community-Based Services",
    "Quality of Life",
    "Health and Well-Being",
    "Mental Health",
    "Addiction Treatment",
    "Statistical Modeling",
    "Childhood Adversity",
    "Family and Parenting",
    "Cross-System Involvement",
    "Latin American Issues",
    "Child Abuse and Neglect",
    "Spatial Analysis",
    "Recovery",
    "Mindfulness",
    "Leadership",
    "LGBTQ+ Studies",
    "Therapeutic Interventions",
    "Child and Family Well-Being",
    "Policy Research",
    "Community Engagement",
    "Economic Development",
    "International Social Work",
    "Asset Building",
    "Food Security",
    "Sustainable Food Systems",
    "Global Social Work",
    "Sex Work and Sex Trafficking",
    "Environmental Justice",
    "Macro Social Work",
    "Population Health",
    "Housing Policy and Homelessness",
    "Social and Economic Inequalities",
    "Child Development",
    "Family Strengthening",
    "Intervention Research",
    "Social Work Education",
    "Immigration and Refugee Studies",
    "Global Health Equity",
    "Climate Justice",
    "Disasters and Extreme Weather Events",
    "Global and Interdisciplinary Research",
    "Children and Families",
    "Infant and Early Childhood Mental Health",
    "Social Determinants of Health",
    "Access to Healthcare",
    "Poverty and Economic Inequality",
    "Trauma Social Work Practice",
    "Healing Justice",
    "Social Work Pedagogy",
    "Transformative Social Work Practices",
    "Substance Abuse Treatment",
    "Mutual Aid Based Programs",
    "Social Network Analysis",
    "Mental Health Services Research",
    "Therapeutic Communities",
    "Child Maltreatment",
    "Resilience",
    "Childhood Trauma",
    "Adolescent Substance Use",
    "Fathers and Fathering"
],
"College of Veterinary Medicine - The Department of Veterinary Preventive Medicine": [
    "Infectious Disease Epidemiology",
    "Epidemiological Tools for Disease Control",
    "Swine Diseases",
    "Infectious Diseases",
    "Antimicrobial Use",
    "Zoonotic Diseases",
    "Animal Models",
    "Laboratory Animal Care",
    "Milk Quality",
    "Mastitis",
    "Dairy",
    "Staphylococcus Aureus Epidemiology",
    "Udder Health",
    "Wildlife Health",
    "Emerging Diseases",
    "Chronic Diseases in Wildlife",
    "Public Health Policy",
    "Zoo & Wildlife Conservation Medicine",
    "Ecosystem Health",
    "Marine and Freshwater Animal Diseases",
    "Environmental Stressors",
    "One Welfare and Sustainability",
    "Conservation",
    "Aquatic Biology",
    "Lab Animal Housing Conditions and HPA Axis Impact",
    "Clinical Treatments and Environmental Enrichment",
    "Humane Experimental Technique",
    "Infectious Disease Modeling",
    "International Disease Surveillance and Control",
    "Bayesian Statistics",
    "Food Safety",
    "Antimicrobial Resistance",
    "Small Ruminant Medicine and Surgery",
    "Epidemiology of Foodborne Pathogens",
    "Cattle Health and Welfare",
    "Gut Microbiome",
    "Pulmonary Immunology",
    "Respiratory Physiology",
    "Farm Animals",
    "Population Medicine",
    "Farm Management",
    "Dairy Nutrition",
    "Production Medicine",
    "Goat Production Management",
    "Herd Health",
    "Animal Welfare",
    "Public Health",
    "Inflammatory Bowel Disease",
    "Colon Cancer",
    "Shelter Animal Health",
    "Equine Studies",
    "Vector-Borne Disease",
    "Disease Ecology",
    "Precision Technologies",
    "Animal Nutrition",
    "Antimicrobial Stewardship",
    "Cardiovascular Disease",
    "Medical Device Development",
    "Safety Pharmacology"
],
"College of Veterinary Medicine - The Department of Veterinary Biosciences": [
    "Mucosal Immunology",
    "Innate Immune Responses",
    "Adjuvants and Mucosal Vaccines",
    "Mucosal Allergic Responses",
    "Flow Cytometry",
    "T-Cells",
    "Function and Phenotype of Freshwater Mussel Hemocytes",
    "Immunophenotyping of Hematopoietic Neoplasia",
    "Epithelial Cell Homeostasis",
    "Inflammatory Diseases",
    "Protein-Protein Interaction",
    "Immune Responses",
    "Gut Flora Interaction",
    "Comparative Pathology",
    "Mouse Models",
    "Laboratory Animal Translational Models",
    "Neuropathology",
    "Neuro-Oncology",
    "Quantitative Digital Pathology",
    "Musculoskeletal Pathology",
    "Hemoparasites",
    "Immunocytochemistry",
    "Exotic Animal Pathology",
    "Molecular Pathogenesis",
    "Retrovirus Replication",
    "Vitamin D in Cancer",
    "Canine Studies",
    "Benign Prostatic Hyperplasia",
    "Dermatopathology",
    "Respiratory Pathology",
    "Virus Genome Biology",
    "Vaccine Development",
    "Flavivirus Pathogenesis",
    "Immunological Processes",
    "Pathogen Evolution",
    "Cancer Treatment",
    "Genomics",
    "Systems Biology",
    "Laboratory Animal Pathology",
    "Fungal Infections",
    "Viral Replication",
    "mRNA Capping",
    "Emerging Viruses",
    "Cell Signaling",
    "Cancer Biology",
    "Tumor Suppressors",
    "Drug Resistance",
    "Tissue Repair",
    "Intracellular Bacteria Signaling",
    "Type IV Secretion",
    "Ehrlichia and Anaplasma Mechanisms",
    "Genome Analysis",
    "Transcriptome Profiling",
    "Viral Infections",
    "Viral Transmission",
    "Oncogenic Viruses",
    "Chronic Viral Infections",
    "Veterinary Forensic Science",
    "Clinical Pathology",
    "Virology",
    "Pathogenesis",
    "Vaccines",
    "Heat Shock Proteins",
    "Immunity",
    "Neuroinflammation",
    "HTLV-1",
    "Oncogenesis",
    "Gene Regulation",
    "Host-Pathogen Interactions",
    "Epidemiology",
    "Tropical Medicine",
    "Reproductive Pathology",
    "Reproductive Physiology",
    "Comparative Theriogenology",
    "Diagnostic Pathology",
    "In Vivo Microscopy",
    "Molecular Mechanisms",
    "Vector-Borne Diseases",
    "Pathogenic Bacteria",
    "Disease Intervention",
    "Feline Disease Pathogenesis",
    "Gastrointestinal Disease",
    "Parasitic Diseases",
    "Molecular Diagnostics",
    "Inflammation and Neoplasia",
    "Retrovirus-Host Interactions",
    "Coronavirus Entry Inhibitors",
    "Cancer Pathology",
    "Cancer Immunology",
    "Comparative Science",
    "Virus Entry",
    "Virus-Host Interactions",
    "Regenerative Medicine"
],
"John Glenn College of Public Affairs": [
    "Qualitative Methodologies",
    "Nonprofits",
    "Philanthropy",
    "Inequality",
    "Social Change",
    "Advocacy",
    "Renewable Energy",
    "Carbon Management",
    "Food-Energy-Water Nexus",
    "Stakeholder Engagement",
    "Public Private Partnerships",
    "Contracting and Contract Management",
    "Democratization",
    "Strategy and Strategic Planning",
    "Public Participation",
    "Social Equity",
    "Food Policy and Governance",
    "Engaged Research",
    "Public Policy Analysis",
    "Energy Economics",
    "Energy and Environmental Policy",
    "Economic Resilience",
    "Risk and Decision Analysis",
    "Critical Infrastructure and Homeland Security Policy",
    "Regulation and Deregulation",
    "Urban and Regional Economic Development",
    "Housing",
    "Crime",
    "Public Finance",
    "AI",
    "Data and Public Governance",
    "Public Interest Technology",
    "Leadership",
    "Organizational Behavior",
    "Policing",
    "Diversity, Equity and Inclusion",
    "Criminal Justice Policy",
    "Education",
    "Workforce Development",
    "Data Sciences",
    "International Development",
    "Economic and Community Development",
    "Urban and Regional Economics",
    "State and Local Public Policy",
    "Economic Development Professional Practice",
    "Workforce Policy and Governance",
    "Manufacturing Policy",
    "Utility Regulation",
    "Food Policy and Marketing",
    "Food Safety and Nutrition Economics",
    "Corporate Social Responsibility and Sustainability",
    "Affordable Housing",
    "Poverty Alleviation",
    "Social Networks",
    "State and Local Politics",
    "Education Policy",
    "Direct Democracy",
    "State and Local Taxation",
    "Revenue Forecasting",
    "State and Local Economic Development Incentive Programs",
    "Public Information Systems",
    "Information and Technology Governance",
    "Information Policy and Law",
    "Education Governance and Policy",
    "Public Administration",
    "Political Economy",
    "Computational Methods",
    "Organizational Institutionalism",
    "Community Philanthropy",
    "Justice Philanthropy",
    "Sexual Harassment",
    "Bibliometrics",
    "Housing and Urban Economics",
    "Consumer Finance and Financial Inclusion",
    "Policy Implementation and Analysis",
    "Drug Policy",
    "Public Health Policy",
    "Qualitative and Mixed Methods",
    "Hard-to-Reach Populations",
    "Harm Reduction",
    "Intersectional Stigma",
    "Administrative History",
    "Comparative Government",
    "Epistemology of Public Administration",
    "Social Ontology of Government",
    "Environmental Policy",
    "Environmental Law",
    "Environmental and Economic Sociology",
    "Bureaucracy",
    "Organizations",
    "Civic Engagement",
    "Social Movements",
    "Criminology",
    "Justice-Involved Youth",
    "Applied Research",
    "Evaluation Research",
    "Space and Place",
    "Health",
    "Public and Nonprofit Management",
    "Public Policy",
    "Child and Family Policy",
    "Network Analysis",
    "Complex Systems Theory",
    "Federal Budgeting",
    "Science, Technology and Innovation Policy",
    "Labor Economics",
    "Race and Racialization"
],
"College of Public Health": [
    "Infectious Diseases",
    "Vaccine Acceptance",
    "Graphic Medicine",
    "Disease Modeling",
    "Health Disparity",
    "Psychosocial Influences on Children's Growth and Development",
    "Childhood Obesity Prevention",
    "Imputation Methods for Missing Data",
    "Selection Bias for Nonprobability Samples",
    "Group-Randomized Trials",
    "Statistical Methods for High-Dimensional Datasets",
    "Genomics",
    "Mixture Cure Models",
    "Ordinal Response Models",
    "Drug Overdose Prevention",
    "Child Maltreatment/Family Violence",
    "Statistical Modeling",
    "Spatial Analysis",
    "Intersection of Child Welfare and Legal System",
    "Public Health Law and Policy",
    "Health Care Law and Policy",
    "Tobacco Policy",
    "Global Public Health",
    "Natural and Manmade Disasters",
    "Emergencies and Other Crises",
    "Health Services Research: Access and Quality of Health Care",
    "Health Policy and Health Reform",
    "Environmental Health",
    "Tobacco Products",
    "Tobacco Emissions",
    "Tobacco Control",
    "Analytical Chemistry",
    "Inhalation Toxicology",
    "Environmental Risk Assessment",
    "Behavioral Oncology",
    "Cancer Prevention",
    "Implementation Science",
    "Community Engagement",
    "Community-Based Prevention Marketing",
    "Community-Based System Dynamics",
    "Social Technology",
    "Minority Health",
    "Social Determinants of Health",
    "Social Justice",
    "Cancer Epidemiology",
    "Women’s Health",
    "Racial Disparities",
    "Molecular Epidemiology",
    "Screening and Early Detection",
    "Smoking Cessation",
    "Tobacco Use Surveillance",
    "Tobacco Regulatory Science",
    "Management Practices",
    "Clinical Informatics",
    "Program Evaluation",
    "Dissemination & Implementation Science",
    "Developmental Neurobiology",
    "Behavioral Neurobiology",
    "Environmental and Biochemical Toxicology",
    "Dispersion Modeling of PAHs",
    "Structural Biology",
    "Environmental-Exposure Health Assessment",
    "Recovery Strategies for Minoritized Populations",
    "Adverse Health Factors in Aging Populations",
    "Drowning and Submersion Injuries",
    "Systems Science",
    "Agent-Based Modeling",
    "Birth Outcomes",
    "Infant Mortality",
    "Environmental Epidemiology",
    "Air Pollution",
    "Opioid Epidemic",
    "Food Insecurity",
    "Smart Cities",
    "Health Economics",
    "Reducing Cancer Disparities",
    "Healthy Food Environments",
    "Survival Analysis",
    "Epidemiologic Methods",
    "Stochastic Processes",
    "Phylogenetics",
    "Causal Inference",
    "Variable Selection",
    "Measurement Error",
    "Sampling Designs",
    "STI Prevention",
    "Spatial Statistics",
    "Bayesian Modeling",
    "Environmental Pesticides",
    "Mental Health",
    "Human Nutrition",
    "Censored Regression",
    "Mixed-Effects Models",
    "Longitudinal Data",
    "Missing Data Analysis",
    "Reproductive Justice",
    "Social Epidemiology",
    "Maternal Health",
    "Adverse Birth Outcomes",
    "Psychiatric Epidemiology",
    "Maternal and Child Health",
    "Building Water Systems",
    "Healthy Indoor Spaces",
    "Sustainability and Risk Assessment",
    "Risk Analysis Methodology",
    "Cumulative Risk Assessment",
    "Water Treatment and Wastewater Reuse",
    "Cerebrovascular Disease",
    "Prognostic Models",
    "Green Space",
    "Autism",
    "GIS",
    "Machine Learning",
    "Cloud Computing",
    "Health Care Access Barriers",
    "Financial Burdens for Vulnerable Populations"
],
"Moritz College of Law": [
    "Criminal Law and Procedure",
    "Social Movements",
    "Clemency",
    "Criminal Record Relief",
    "Death Penalty",
    "Drug Policy",
    "Marijuana Reform",
    "Sentencing",
    "Health Law",
    "Public Health",
    "Tobacco Law and Policy",
    "US Supreme Court",
    "Antitrust",
    "Corporate Law",
    "Financial Regulation",
    "Wills, Trusts & Estates",
    "AI, Data Analytics, and the Law",
    "Computer Law",
    "Copyright",
    "Cyberlaw and Cybersecurity",
    "Intellectual Property",
    "Law and Computer Science",
    "Patent Law",
    "Privacy Law",
    "Software Law",
    "Torts",
    "Alternative Dispute Resolution",
    "Chinese Law",
    "Civil Litigation and Procedure",
    "Foreign Trade and Investment",
    "International Business Transactions",
    "International Intellectual Property",
    "Negotiation",
    "Arbitration",
    "Clinical Education",
    "Experiential Education",
    "Labor and Employment",
    "Mediation",
    "Civil Rights and Civil Liberties",
    "Constitutional Law",
    "Disability Law",
    "Education Law",
    "Feminist Legal Theory",
    "Lesbian, Gay, Bisexual, and Transgender Rights",
    "Election Law",
    "Legal Writing and Research",
    "Legislation & Regulation",
    "Child Abuse and Neglect",
    "Children and the Law",
    "Family Law",
    "Juvenile Law",
    "Support and Visitation",
    "Campaign Finance",
    "Voting Rights",
    "Immigration",
    "Policing",
    "Commercial Law",
    "Consumer Law",
    "Contracts",
    "Electronic Commerce",
    "Entrepreneurship",
    "Law and Economics",
    "Legal History",
    "Small Business Finance",
    "Medical Malpractice",
    "Federal Courts",
    "Employment Discrimination",
    "Sexual Harassment",
    "Global Governance",
    "Human Rights",
    "International Law",
    "International Organizations",
    "International Relations Theory",
    "Law of Armed Conflict",
    "Law of International Watercourses",
    "Law of the Sea",
    "Middle East Politics",
    "Public International Law",
    "Critical Theory",
    "AI and Data Ethics and Governance",
    "Bioethics",
    "Legal Ethics",
    "Legal Profession",
    "National Security",
    "Professional Responsibility",
    "Secrecy",
    "Tax Law and Policy",
    "Business of Law",
    "Legal Tech",
    "Online Dispute Resolution",
    "Diversity",
    "Law and Political Economy",
    "Environmental Law",
    "Media and Democracy",
    "Nonprofit Organizations",
    "Venture Capital",
    "Food Law"
],
"College of Food, Agricultural, and Environmental Sciences - Animal Sciences": [
    "Swine Infectious Diseases",
    "Swine Production, Management, and Welfare",
    "Food Animal Health",
    "Meat Science",
    "Muscle Biology",
    "Grazing Systems",
    "Environmental Impact Assessment",
    "Poultry",
    "Equine Studies",
    "Immunology",
    "Reproductive Biology",
    "Endocrinology",
    "Molecular and Cellular Biology",
    "Dairy",
    "Nutrition",
    "Mastitis",
    "Mammary Physiology",
    "Fermentation Biology",
    "Microbiology",
    "Reproductive Physiology",
    "Beef",
    "Reproductive Biotechnologies",
    "Viral and Bacterial Mucosal Vaccines",
    "Influenza",
    "Porcine Reproductive and Respiratory Syndrome",
    "Salmonella",
    "Zoonotic Diseases",
    "Mucosal Vaccine Delivery Platforms",
    "Adjuvants and Immune Modulators",
    "Veterinary Medicine",
    "Plant Animal Agrosecurity Research",
    "BSL-3 Training",
    "IACUC"
],
"College of Food, Agricultural, and Environmental Sciences - Agricultural, Environmental and Development Economics": [
    "Economics of Conservation",
    "Ecosystem Service Provision",
    "Agricultural Production",
    "Environmental Economics",
    "Conservation Policies",
    "Development",
    "Health",
    "Experimental Economics",
    "Non-market Valuation",
    "Bioeconomics",
    "Coupled Models of Human-Natural Systems",
    "Coastal Systems",
    "Food Accessibility",
    "Food Security",
    "Behavioral Economics",
    "Economics of Trust",
    "Health Economics",
    "Health Policy and Regulation",
    "Policy Analysis",
    "Marketing and Consumer Economics",
    "Resource and Environmental Economics",
    "Regional Development",
    "Land Use Economics",
    "Urban Economics",
    "Applied Spatial Analysis",
    "Farm Labor",
    "Farm Household Dynamics",
    "Agricultural Finance",
    "Agribusiness",
    "Applied Econometrics",
    "Agricultural Innovation and Technology Adoption",
    "Climate Change",
    "Discrete Choice Modeling",
    "Computational Economics",
    "International Economic Development",
    "Agricultural Finance and Insurance",
    "Agricultural and Environmental Policy",
    "Food Security",
    "International Trade",
    "Commodity Pricing",
    "Industrial Organization",
    "Impostor Phenomenon",
    "Community and Regional Economics",
    "Spatial Modeling",
    "Regional Economic Development and Growth",
    "Poverty",
    "Food Waste",
    "Product Quality",
    "Information Policy",
    "Agricultural Marketing",
    "Farm Management",
    "Nutrient Management",
    "Corporate Environmentalism",
    "Financial Economics",
    "International Trade & Policy",
    "Natural Resource & Environmental Economics",
    "Modeling Land-Use/Land-Cover Change",
    "Economics of Non-Point Source Pollution",
    "Food Value Chains",
    "Production Economics",
    "Economic Geography",
    "Place-Based Policies"
],
"College of Arts and Sciences - Department of Statistics": [
    "Meta Analysis",
    "Survey Sampling",
    "Bayesian Statistics",
    "Network Analysis",
    "Nonparametric Methods",
    "Mathematics Education",
    "Statistics Education",
    "Instructional Technology",
    "Higher Education Affairs",
    "Active Learning",
    "Distance Education",
    "Causal Inference",
    "Missing Data",
    "Mediation Analysis",
    "Observational Studies",
    "Survival Analysis",
    "Time Series",
    "Uncertainty Quantification",
    "Inverse Problems",
    "Functional Data Analysis",
    "Spatial and Spatio-Temporal Statistics",
    "Model Uncertainty and Selection",
    "Monte Carlo and MCMC Methods",
    "Statistical Computing",
    "Graphical Models",
    "Applied Probability",
    "Statistical Genetics",
    "Phylogenetics",
    "Population Genetics",
    "Computational Biology",
    "Shape Analysis",
    "Image Analysis",
    "Statistical Learning",
    "Multivariate Analysis",
    "Classification",
    "Statistical Genomics and Bioinformatics",
    "High-Dimensional Data Analysis",
    "Robust Methods",
    "Models for Latent Variables",
    "Neuroimaging Data Analysis",
    "Time Series Analysis",
    "Statistical Graphics",
    "Computer Experiments",
    "Percolation",
    "Interacting Particle Systems",
    "Stochastic Processes",
    "U-Statistics",
    "Conformal Prediction",
    "Decision Theory",
    "Image/Video Content Analysis"
],
"College of Arts and Sciences - Department of English": [
    "Critical and Cultural Theory",
    "Disability Studies",
    "Gender and Sexuality Studies",
    "Literature: Twentieth- and Twenty-first-century",
    "Folklore",
    "Literature: U.S. Ethnic and Postcolonial",
    "Business, Technical and Professional Writing",
    "Digital Media Studies",
    "Film and Popular Culture",
    "Writing, Rhetoric, and Literacy",
    "History of the Book",
    "Literature: Eighteenth-century British",
    "Textual Studies and Text Editing",
    "Literature: Early and Nineteenth-century U.S.",
    "Medical Humanities",
    "Environmental Humanities",
    "Creative Writing",
    "Literature: Renaissance",
    "Narrative",
    "Poetry and Poetics",
    "Bible as Literature",
    "Literature: Nineteenth-century British",
    "Literature: Old English and Medieval",
    "Linguistics",
    "Human Rights and English Studies",
    "Twentieth-century British and American literature",
    "Feminist theory",
    "Critical theory"
],
"College of Arts and Sciences - Department of Economics": [
    "Contract Theory",
    "Industrial Organization",
    "Game Theory",
    "Experimental Economics",
    "Auctions",
    "Microeconomic Theory",
    "Mathematical Economics",
    "Development Economics",
    "Labor Economics",
    "Economics of the Household",
    "Econometrics",
    "Macroeconomics",
    "Financial Economics",
    "Economic Theory",
    "Mechanism Design",
    "Experimental Methods in Economics",
    "Behavioral Economics",
    "Anti-Trust and Industrial Organization Issues",
    "Economic Development",
    "Monetary Economics",
    "Health Economics",
    "Applied Econometrics",
    "Auction Theory",
    "Micro Theory",
    "Economics of Education",
    "Economic Demography",
    "Economic History",
    "Econometric Theory",
    "Empirical Industrial Organization",
    "Auction Models",
    "Labor Markets",
    "Firm Dynamics",
    "Sovereign Debt",
    "Computational Methods",
    "International Macroeconomics",
    "Sovereign Debt and Default",
    "Herding Models",
    "Market Uncertainty",
    "Applied Microeconomics",
    "Antitrust",
    "Regulation"
],
"College of Arts and Sciences - School of Earth Sciences": [
    "Geodetic Science",
    "Water, Climate and the Environment",
    "Earth History",
    "Solid Earth Dynamics"
],
"College of Arts and Sciences - Department of Theatre, Film, and Media Arts": [
    "Theatre Studies",
    "Moving-Image Production",
    "Film Studies",
    "Design",
    "Acting",
    "Critical and Cultural Theory",
    "Film and Popular Culture",
    "Literature: U.S. Ethnic and Postcolonial",
    "History of the Book",
    "Literature: Renaissance",
    "Textual Studies and Text Editing"
],
"College of Arts and Sciences - Department of Mathematics": [
    "Uncertainty Quantification",
    "Data Sciences",
    "Numerical Analysis",
    "Algebraic Geometry",
    "Combinatorics",
    "Geometric Topology",
    "Geometric Group Theory",
    "Low-dimensional Topology",
    "Applied Mathematics",
    "Mathematical Biology",
    "Dynamical Systems",
    "Ergodic Theory",
    "Ergodic Ramsey Theory",
    "Polynomial Szemeredi Theorems",
    "Number Theory",
    "Knot Theory",
    "Topology",
    "Knot & Graph Theory",
    "Representation Theory",
    "Representation Theory of Real Semisimple Lie Groups",
    "Integrable Systems",
    "Singularity Theory",
    "Hodge Theory",
    "Differential & Partial Differential Equations",
    "Orthogonal Polynomials",
    "Asymptotic Analysis",
    "Analysis",
    "Ordinary and Partial Differential Equations",
    "Mathematical Physics",
    "Borel Summability",
    "Analyzable Functions",
    "Complex Dynamics",
    "Spectral Theory",
    "Special Functions",
    "Random Matrices",
    "Mathematical Logic and Foundations",
    "Analytic Number Theory",
    "L-functions",
    "Converse Theorems",
    "Probability Theory",
    "Brownian Motion",
    "Differential Geometry",
    "Einstein Manifolds",
    "Mathematical Modeling of Cell Polarization & Chemotaxis",
    "Tropical Geometry",
    "Non-Archimedean Geometry",
    "Complex Analysis",
    "Mathematical Education",
    "Applied Algebraic Topology",
    "Ergodic Theory & Dynamical Systems",
    "Cluster Algebras",
    "Classical and Quantum Integrable Systems",
    "Flat Connections",
    "Quantum Groups",
    "Braid Groups",
    "Homotopy Theory",
    "Algebraic Topology",
    "Behavioral Ecology",
    "Coerced Cooperation",
    "Evolution of Cooperative Behavior",
    "Mathematical Modeling",
    "Geometric Analysis",
    "Metric Geometry",
    "Automorphic Forms",
    "Sieve Methods",
    "Quantum Unique Ergodicity",
    "Financial Mathematics",
    "Computational Number Theory",
    "Random Matrix Models for L-functions",
    "Graph Theory",
    "Combinatorial Algebraic Geometry",
    "Arithmetic Geometry",
    "Functional Analysis",
    "Harmonic Analysis",
    "Real Analysis",
    "3-dim Manifolds & Knots",
    "Quantum Field Theories",
    "Reps of Mapping Class Groups",
    "Dynamics on Nilmanifolds",
    "Function Spaces",
    "Integral Inequalities",
    "Function Theory",
    "Symplectic Topology & Geometry",
    "Mirror Symmetry",
    "Gromov-Witten Theory",
    "Moduli Spaces",
    "Models of Infectious Disease Dynamics",
    "Parameter Estimation",
    "Neuroscience",
    "Special Functions",
    "Spectral Zeta Functions",
    "Sturm-Liouville Operators",
    "Real Algebraic Geometry",
    "Shape Comparison & Matching",
    "Computational Topology",
    "Topological Data Analysis",
    "Machine Learning",
    "Clustering",
    "Complex Geometry",
    "Actuarial Science",
    "Torsion Theory",
    "Group Theory and Group Rings",
    "Scientific Computing",
    "Computational Fluid Dynamics",
    "Multiscale Modeling and Computation",
    "Numerical Methods for Nonlinear PDEs",
    "Wave Propagation",
    "Operator Algebras",
    "Quantum Algebra",
    "Extremal Combinatorics",
    "Additive Combinatorics",
    "Analysis on Fractal Sets",
    "Free Boundary Problems",
    "Fluid Mechanics and Turbulence",
    "Several Complex Variables",
    "Quantum Probability",
    "Wick Products",
    "Percolation",
    "Interacting Particle Systems",
    "Discrete Dynamical Systems",
    "Analysis on Metric Spaces",
    "Ramsey Theory",
    "Homological Algebra",
    "Functor Categories",
    "Model Theory of Modules",
    "Theory of Rings and Modules"
],
"College of Arts and Sciences - Department of Classics": [
    "Languages, Literature, and Cultures of Greece and Rome"
],
"College of Arts and Sciences - Department of Chemistry and Biochemistry": [
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Analytical Chemistry",
    "Environmental Chemistry",
    "Organic Chemistry",
    "Biochemistry",
    "Biophysics",
    "Chemistry Education"
],
"College of Arts and Sciences - Department of Art": [
    "Departmental",
    "Moving-Image Production",
    "Sculpture",
    "Regional",
    "Glass",
    "Photography",
    "Painting and Drawing",
    "Art & Technology",
    "Printmaking",
    "Ceramics",
    "Foundations"
],
"College of Arts and Sciences - Department of Astronomy": [
    "Galaxy Formation and Evolution",
    "Nuclear and Particle Astrophysics",
    "Supernovae",
    "Gamma-Ray Bursts",
    "Compact Objects",
    "Galactic Structure and Evolution",
    "Stellar Evolution and Structure",
    "Astronomical Instrumentation",
    "Active Galactic Nuclei",
    "Extrasolar Planets",
    "Exoplanets",
    "Gravitational Lensing and Microlensing",
    "Star Formation and ISM",
    "Radio Astronomy",
    "Cosmology and Large-Scale Structure",
    "Atomic Astrophysics",
    "Astronomy Education",
    "Colloquium"
],
"College of Arts and Sciences - Department of African American and African Studies": [
    "Black Girlhood Studies",
    "Black Feminisms",
    "Antiblackness",
    "Critical Theory",
    "Community Engaged Research",
    "Qualitative Research Models",
    "Education Policy",
    "African Studies",
    "Somali Studies",
    "Immigration",
    "Critical Refugee Studies",
    "Carceral Studies",
    "Afro-pessimism",
    "Political Theory",
    "Global and Comparative Labor Studies",
    "Intellectual History",
    "South African Politics and History",
    "Colonialism and Postcolonialism",
    "Race, Public Policy, and Socio-Economic Inequality",
    "Housing and Urban Redevelopment",
    "Black Religion and Cultural Studies",
    "Africana Studies",
    "Elections and Voting",
    "Healthcare and Race",
    "Media, Public Policy, and Politics",
    "Police-Community Relations",
    "Security Studies",
    "Hip Hop Studies",
    "Popular Culture",
    "DJ Performance & Production-Based Studies",
    "Higher Education Administration",
    "African Literature",
    "Race and Ethnicity",
    "Interdisciplinary Cultural Studies",
    "Postcolonial Literature and Theory",
    "Pan-African/Black Atlantic Studies",
    "World Literature",
    "Literary Theory",
    "Nationalism and Modernity",
    "The Civil Rights Movement",
    "Black Women’s Activism",
    "African American History",
    "20th Century US History",
    "Prison Education",
    "Language and Society",
    "Society and Culture",
    "Race, Ethnicity, Religion",
    "Historical, Cultural, and Linguistic Studies",
    "War and Conflict",
    "Black European Studies",
    "European Studies",
    "Post-Socialist Studies",
    "Race and Nationalism",
    "South Slavic Culture",
    "Literature and Film",
    "Student Migration",
    "Ethnomusicology",
    "Cultural Anthropology",
    "Global Black Studies",
    "Museum Studies",
    "Material Culture Studies",
    "Transnational History",
    "History of Colonialism"
],
"College of Arts and Sciences - Department of Anthropology": [
    "Migration",
    "Archaeology",
    "Social-ecological Systems",
    "Evolutionary Anthropology",
    "Medical Anthropology",
    "Cultural Anthropology",
    "Environmental Anthropology",
    "Bioarchaeology",
    "Paleoecology",
    "Behavioral Ecology",
    "Biological Anthropology",
    "Dental Anthropology",
    "Life History",
    "Modern Human Variation",
    "Primatology",
    "Ecological Infectious Diseases",
    "Nutritional Anthropology",
    "Hominid Evolution",
    "Computer Modeling",
    "Global Health"
],
"College of Arts and Sciences - Department of Psychology": [
    "Clinical Psychology",
    "Quantitative Psychology",
    "Behavioral Neuroscience",
    "Decision Psychology",
    "Social Psychology",
    "Cognitive Psychology",
    "Cognitive Neuroscience",
    "Developmental Psychology",
    "Evolutionary Anthropology",
    "Medical Anthropology",
    "Bioarchaeology",
    "Environmental Anthropology",
    "Social-ecological Systems",
    "Primatology",
    "Nutritional Anthropology",
    "Hominid Evolution",
    "Computer Modeling",
    "Global Health"
],
"Fisher College of Business": [
    "Strategy",
    "Production/Operations Management",
    "Sustainability/Corporate Responsibility",
    "Marketing",
    "Logistics/Supply Chain Management",
    "Information Technology",
    "Finance",
    "Real Estate",
    "Corporate Finance",
    "Consumer Finance",
    "Business Law",
    "Business Education",
    "Ethics and Leadership",
    "Human Resources Management",
    "Accounting",
    "Public Policy",
    "International",
    "Industries",
    "Capital Markets",
    "Financial Reporting",
    "Institutional Investors",
    "Taxes and Philanthropy",
    "Nonprofit Accounting",
    "Nonprofit Finances",
    "Nonprofit Governance",
    "Auditing",
    "Earnings Management",
    "Research Methodology",
    "Employee Recruitment",
    "Employee Retention",
    "Organizational Behavior",
    "Performance Management",
    "Training and Development"
],
"College of Engineering - Department of Materials Science and Engineering": [
    "Advanced Forming",
    "Advanced Joining",
    "Additive Manufacturing",
    "Biomaterials",
    "Characterization and Microscopy",
    "Ceramic Science",
    "Cognitive Systems Engineering",
    "Computational Materials Science and Engineering",
    "Corrosion",
    "Data Analytics",
    "Electronic, Photonic, Magnetic Materials",
    "Energy Materials",
    "Mechanical Properties of Materials",
    "Metallic Materials",
    "Optimization",
    "Polymer Processing",
    "Processing and Manufacturing",
    "Smart Integrated Mobility, Manufacturing, and Cyber Security",
    "Sensor Materials and Technologies",
    "Stochastic Modeling & Simulation",
    "Supply Chain Management & Logistics",
    "Systems Automation & Robotics",
    "Systems (Control, Signal Processing, and Computer Vision)",
    "Welding Engineering"
],
"College of Engineering - Department of Electrical and Computer Engineering": [
    "Systems (Control, Signal Processing and Computer Vision)",
    "Solid State Electronics and Photonics",
    "Power & Energy",
    "Nanotechnology and Devices",
    "Electromagnetics",
    "Computer Networks and Communication",
    "Circuits"
],
"College of Engineering - Department of Civil, Environmental, and Geodetic Engineering": [
    "Geodetic Engineering",
    "Environmental Engineering",
    "Transportation Engineering",
    "Infrastructure Engineering",
    "Geotechnical Engineering",
    "Structural and Materials Engineering"
],
"College of Engineering - William G. Lowrie Department of Chemical and Biomolecular Engineering": [
    "Reaction Engineering, Catalysis",
    "Molecular Thermodynamics and Molecular Simulation",
    "Sustainability, Energy, Environment, Process Engineering",
    "Bioengineering, Biotechnology",
    "Polymers, Nanomaterials",
    "Membrane Separations",
    "Colloids, Aerosols, Particle Technology",
    "Fluid Mechanics, Multiphase Flow",
    "Petroleum Engineering"
],
"College of Engineering - Department of Biomedical Engineering": [
    "Molecular, Cell, and Tissue Engineering",
    "Micro/Nanotechnology Biomedical Devices",
    "Biomechanics",
    "Biomaterials",
    "Bioimaging"
],
"College of Engineering - Department of Computer Science and Engineering": [
    "Theory & Algorithms",
    "Software Engineering & Programming Languages",
    "Systems",
    "Networking and Distributed Computing",
    "Computer Graphics",
    "AI",
    "Computer Networks and Communication"
],
"The James, Comprehensive Cancer Center": [
    "Translational Therapeutics",
    "Molecular Carcinogenesis and Chemoprevention",
    "Cancer Biology",
    "Cancer Control",
    "Leukemia and Hematologic Malignancies",
    "Air Pollution",
    "Environmental and Occupational Health",
    "Inhalation Toxicology",
    "Molecular Epidemiology",
    "Environmental Risk Assessment",
    "Urinary Bladder Neoplasms",
    "Veterinary Medicine",
    "Group Randomized Trials",
    "Survival Analysis",
    "Bayesian Nonparametrics",
    "Joint Modeling",
    "Toxicological Risk Assessment",
    "Epigenetics",
    "Biomarkers of Exposure",
    "Biomarkers of Effects",
    "Cancer Risk Factors",
    "Gene-Environment Interactions",
    "Tobacco",
    "Cancer Prevention",
    "Multi-Omics Data",
    "Statistical Methods",
    "Epidemiology",
    "Biosystems Modeling",
    "Applied Probability Theory",
    "Math Biology",
    "Complex Stochastic Systems",
    "Biochemical Reaction Networks",
    "Mathematical Models of Epidemics",
    "Mathematical and Statistical Methods in Genomics",
    "Infectious Disease Epidemiology"
],
"College of Education and Human Ecology": [
    "Access and Equity",
    "Achievement",
    "Adolescent and At-Risk Youth",
    "Anthropology",
    "Assessment",
    "Behavioral Aspects of Health",
    "Biochemistry",
    "Bilingual, Multilingual, and Multicultural Education",
    "Child Development",
    "Civic Education",
    "Cognitive Development",
    "Cognitive Psychology",
    "Community/Youth Development and Organizations",
    "Consumer Economics",
    "Curriculum and Instruction",
    "Developmental/Remedial English",
    "Dietetics and Nutrition",
    "Educational Achievement",
    "Educational Assessment, Testing, and Measurement",
    "Educational Administration",
    "Educational/Instructional Technology",
    "Educational Psychology",
    "Educational Statistics and Research Methods",
    "Elementary Education and Teaching",
    "Endocrinology",
    "Equity",
    "Exercise Physiology",
    "Family and Community Human Services",
    "Family Financial Services",
    "Family Resource Management Studies",
    "Family and Consumer Sciences",
    "Foreign Language Teacher Education",
    "Foods, Nutrition, and Wellness Studies",
    "Gene/Genetic Therapy",
    "Higher Education and Student Affairs (HESA)",
    "Human Development and Family Studies",
    "Human Nutrition",
    "Integrated Studies",
    "International and Comparative Education",
    "Kinesiology and Exercise Science",
    "Learning Technologies",
    "Literacy",
    "Linguistics",
    "Mathematics Teacher Education",
    "Maternal and Child Health",
    "Multicultural Education",
    "Nutrition in Industry",
    "Pre-medicine",
    "Public Health Education and Promotion",
    "Reading Teacher Education",
    "Rural Education",
    "Science Teacher Education",
    "Second Language Learning",
    "Social and Philosophical Foundations of Education (Philosophy of Education)",
    "Social Justice",
    "Sociology",
    "Special Education",
    "Technology Integration",
    "Technology Teacher Education",
    "Urban Education",
    "Vocational Education",
    "Workforce Development and Education",
    "Women's Studies",
    "Young Adult (Adolescent) Literature"
],
"College of Food, Agricultural, and Environmental Sciences - Department of Food, Agricultural and Biological Engineering": [
    "Food Engineering",
    "Agricultural Engineering",
    "Construction Safety",
    "Interface Management",
    "Waste Management",
    "Lean Construction",
    "Building Energy Simulation",
    "High-Performance Green Buildings",
    "Engineering Education",
    "Bioenergy",
    "Environmental Engineering",
    "Machinery Automation",
    "Application Equipment",
    "Data Analytics",
    "Ecohydrology",
    "Vegetation Biophysics",
    "Modeling",
    "Simulation",
    "Remote Sensing",
    "Rubber",
    "Waste Utilization",
    "Sustainable Fillers",
    "Biofuels",
    "Hydroponics",
    "Crop Domestication",
    "Sustainable Buildings",
    "Agricultural Remote Sensing",
    "Agroecosystem Modeling",
    "Precision Agriculture",
    "Occupational Safety & Health",
    "Composting",
    "Corn and Cellulosic Ethanol",
    "Bioprocessing",
    "Alternative Natural Rubber Bioprocesses",
    "Ecological Engineering",
    "Systems Ecology",
    "Ecological Modeling",
    "Greenhouse Engineering",
    "Biosystem Engineering",
    "Digital Agriculture",
    "Automation",
    "Robotics",
    "Polymer Science",
    "Engineering",
    "Humanitarian Engineering",
    "Water Quality",
    "Stormwater Management",
    "Hydrology",
    "Agricultural Air Quality"
],
"College of Food, Agricultural, and Environmental Sciences - Department of Plant Pathology": [
    "Plant bacteriology",
    "Evolution",
    "Pathogen emergence",
    "Disease epidemiology",
    "Disease management",
    "Plant microbiome",
    "Microbial ecology",
    "Epidemiology",
    "Plant diseases",
    "Molecular Plant Virology",
    "Plant Resistance",
    "Mycology",
    "Genomics",
    "Metabolism",
    "Molecular Ecology",
    "Plant Immunity",
    "Plant-Microbe Interactions",
    "Microbial control",
    "Biochemical mechanisms",
    "Genetic mechanisms",
    "Molecular mechanisms"
],
"Department of Physics": [
    "Surface and Interface Science",
    "Nanoscale Electronic Materials",
    "Molecular Beam Epitaxy",
    "Nuclear",
    "High Energy Theory",
    "High Energy Physics",
    "Dark Matter",
    "Condensed Matter",
    "Astrophysics",
    "Cosmic Rays",
    "Neutrinos",
    "High-Energy Astronomy",
    "Multi-Messenger Astronomy",
    "Nuclear Astrophysics",
    "Cognitive Science",
    "Physics Education",
    "Computational Nuclear Physics",
    "Low-Energy Nuclear Theory",
    "Technology Education",
    "Science",
    "Atomic Physics",
    "Molecular Physics",
    "Optical Physics",
    "Ultra-High-Energy Neutrino Experiments",
    "Physics",
    "Astrophysics and Cosmology",
    "Physics Education Research",
    "Biomagnetism",
    "Condensed Matter Experiment",
    "Statistical Physics",
    "Mathematical Physics",
    "Classical Condensed Matter Physics",
    "Quantum Condensed Matter Physics",
    "Cosmology",
    "Particle Physics",
    "Quantum Communication",
    "Quantum Computing",
    "Dynamics of Classical Networks",
    "Spin Dynamics",
    "Nanoscale Magnet",
    "Discovery and Study of the Top Quark",
    "High Energy Gamma Rays",
    "Experimental Particle Astrophysics",
    "Radio Detector Development and Analysis",
    "Physics of Medical Imaging",
    "Dark Energy"
]

}